apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # Put non-sensitive runtime configuration here (strings)
  API_GATEWAY_BASE: "https://api.example.com"
  NODE_ENV: "production"
  # Add other config keys used by your services
