# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s     # How often to scrape targets
  evaluation_interval: 15s # How often rules are evaluated

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Kubernetes API for node/pod metrics
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Scrape your services (exposed on /metrics)
  - job_name: 'ecommerce-services'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: (auth-service|product-service|order-service|cart-service|payment-service|notification-service|api-gateway)
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        replacement: $1:3000
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: service
